# Generated by Django 4.2.1 on 2023-05-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_room_capacity_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
