# Generated by Django 4.2.1 on 2023-05-30 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_room_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='students_in_room',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
