# Generated by Django 4.2.1 on 2023-06-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_utilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
    ]
