# Generated by Django 4.2.1 on 2023-06-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_utilities_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
    ]
