# Generated by Django 4.2.1 on 2023-06-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_complaint_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='room_capacity',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
