# Generated by Django 4.2.1 on 2023-06-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_hostel_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
