# Generated by Django 4.2.1 on 2023-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_student_course_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
