# Generated by Django 4.0.6 on 2024-03-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/')),
                ('link', models.URLField()),
                ('days', models.IntegerField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
    ]
