# Generated by Django 4.0.6 on 2024-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira')], default='USD', max_length=3),
        ),
    ]
