# Generated by Django 5.0.1 on 2024-01-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="total_rating",
            field=models.IntegerField(default=0),
        ),
    ]
