# Generated by Django 5.0.1 on 2024-01-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_recipe_average_rating_recipe_rating_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipebook",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
