# Generated by Django 5.0.1 on 2024-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_recipebook_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipebook",
            name="comments",
            field=models.ManyToManyField(blank=True, to="core.comment"),
        ),
    ]
