# Generated by Django 5.0.1 on 2024-01-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_recipebook_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipebook",
            name="about",
            field=models.TextField(blank=True),
        ),
    ]
