# Generated by Django 5.0.1 on 2024-01-18 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_recipebook_about"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipebook",
            name="likes",
        ),
        migrations.AddField(
            model_name="recipebook",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_recipe_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
