# Generated by Django 5.0.1 on 2024-01-19 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_ingredient_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipecomment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="recipebook",
            name="comments",
            field=models.ManyToManyField(blank=True, to="core.recipecomment"),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
