# Generated by Django 5.0.1 on 2024-01-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_recipecomment_likes_alter_recipebook_comments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="compulsory_ingredients",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="optional_ingredients",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="ingredients", to="core.ingredient"
            ),
        ),
    ]
