# Generated by Django 5.0.1 on 2024-01-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_recipe_cooking_type_alter_recipe_food_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
